# Generated by Django 5.0.4 on 2024-06-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school_name',
            field=models.CharField(default='Natural Log'),
            preserve_default=False,
        ),
    ]
