# Generated by Django 5.0.4 on 2024-06-02 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='school_name',
        ),
    ]
