# Generated by Django 5.0.4 on 2024-06-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_remove_teacher_school_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
