# [START runtime]
# [START gaeflex_py_django_app_yaml]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT wsgi

beta_settings:
    cloud_sql_instances: possible-coast-387309:us-west1:bridger-dev-db

runtime_config:
  python_version: 3.7


# [END gaeflex_py_django_app_yaml]
# [END runtime]
