# Generated by Django 5.0.4 on 2024-06-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number_of_classes',
            field=models.IntegerField(default=10),
        ),
    ]
