# Generated by Django 5.0.4 on 2024-06-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_course_number_of_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='number_of_classes',
            new_name='number_of_lessons',
        ),
    ]
