# Generated by Django 5.0.4 on 2024-06-01 03:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_courseregistration_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
