# Generated by Django 5.0.4 on 2024-06-01 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_courseregistration_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='code',
        ),
    ]
