# Generated by Django 5.0.4 on 2024-06-01 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_courseregistration_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='course_registration',
            new_name='registration',
        ),
    ]
