# Generated by Django 5.0.4 on 2024-06-01 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_course_registration_lesson_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='booked_date',
            new_name='booked_datetime',
        ),
    ]
