# Generated by Django 5.0.4 on 2024-06-02 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_lesson_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
    ]
