# Generated by Django 5.0.4 on 2024-06-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('student', '0009_remove_lesson_course'),
        ('teacher', '0006_teacher_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ManyToManyField(related_name='student', to='school.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(related_name='student', to='teacher.teacher'),
        ),
    ]
