# Generated by Django 5.0.4 on 2024-06-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_remove_student_teacher_courseregistration_favorite_and_more'),
        ('teacher', '0006_teacher_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(related_name='student', through='student.StudentTeacherRelation', to='teacher.teacher'),
        ),
    ]
