# Generated by Django 5.0.4 on 2024-06-02 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_student_teacher'),
        ('teacher', '0006_teacher_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentteacherrelation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_relation', to='student.student'),
        ),
        migrations.AlterField(
            model_name='studentteacherrelation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relation', to='teacher.teacher'),
        ),
    ]
