# Generated by Django 5.0.4 on 2024-06-02 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_studentteacherrelation_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentteacherrelation',
            old_name='favorite',
            new_name='favorite_teacher',
        ),
    ]
