# Generated by Django 5.0.4 on 2024-06-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_rename_favorite_studentteacherrelation_favorite_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentteacherrelation',
            name='favorite_student',
            field=models.BooleanField(default=False),
        ),
    ]
