# Generated by Django 5.0.4 on 2024-06-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_studentteacherrelation_favorite_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='used_lessons',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
