# Generated by Django 5.0.4 on 2024-06-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_courseregistration_used_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='used_lessons',
            field=models.IntegerField(default=0),
        ),
    ]
