# Generated by Django 5.0.4 on 2024-06-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_alter_courseregistration_used_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
