# Generated by Django 5.0.4 on 2024-06-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_courseregistration_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='target_class',
        ),
    ]
